version: "3"

services:
  app:
    build: docker/php
    volumes:
      - ./:/app
    depends_on:
      - mailcatcher
    env_file:
      - .env

  nginx:
    image: nginx:1.12-alpine
    ports:
      - 82:80
    volumes:
      - ./:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1089:1080

  dball:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - 3300:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forma
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
