<?php

namespace forma\modules\selling\controllers;

use forma\extensions\editable\EditCellAction;
use forma\modules\selling\records\selling\Selling;
use forma\modules\selling\services\SellingService;
use forma\modules\warehouse\services\RemainsService;
use Yii;
use forma\modules\selling\records\sellingproduct\SellingProduct;
use forma\modules\selling\services\NomenclatureService;
use forma\modules\selling\widgets\NomenclatureView;
use yii\web\Controller;
use yii\web\Response;
use yii\web\HttpException;
use yii\widgets\ActiveForm;

class NomenclatureController extends Controller
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionAddPosition()
    {
        /** @var SellingProduct $model */
        $post = Yii::$app->request->post();
        $sellingId = $post['SellingProduct']['selling_id'];
        $selling = Selling::findOne($sellingId);
        $selling_token = $selling->getSellingToken();
        if(Yii::$app->user->isGuest){
            if(!isset($post['selling_token']) || is_null($post['selling_token'])) return false;
            if($selling_token != $post['selling_token']) return false;
        }
        $model = NomenclatureService::addPosition(Yii::$app->request->post());

        return NomenclatureView::widget([
            'sellingId' => $model->selling_id,
            'model' => $model,
            'selling_token' => $post['selling_token'] ?? null
        ]);
    }

    public function actionDeletePosition($id)
    {
        /** @var SellingProduct $model */
        $selling_token_get = Yii::$app->request->get('selling_token');
        $selling_token = Selling::findOne(SellingProduct::findOne($id)->selling_id)->selling_token;
        if(Yii::$app->user->isGuest){
            if(!isset($selling_token_get) || is_null($selling_token_get)) return false;
            if($selling_token != $selling_token_get) return false;
        }
        $model = NomenclatureService::deletePosition($id);


        //$selling = Selling::findOne($model->selling_id);
        return NomenclatureView::widget([
            'sellingId' => $model->selling_id,
            'model' => $model,
            'selling_token' => $selling_token_get
        ]);
    }

    public function actionGetProductCost()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $response = ['success' => true];

            $productId = Yii::$app->request->post('productId');
            $sellingId = Yii::$app->request->post('sellingId');
            $costType = Yii::$app->request->post('costType');

            $cost = NomenclatureService::getProductCost($productId, $sellingId, $costType);
            
            return array_merge($response, ['cost' => $cost]);
        }

        throw new HttpException(404 ,'Page not found');
    }

    public function actionChangeNomenclatureCell()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return NomenclatureService::changeCell(Yii::$app->request->post());
    }

    public function actionChangeUnitCost()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return NomenclatureService::changeCell(Yii::$app->request->post(), 'costLabel');
    }

    public function actionValidate()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;

            /** @var SellingProduct $model */
            $model = NomenclatureService::createPosition();
            $model->load(Yii::$app->request->post());
            return ActiveForm::validate($model);
        }
    }

    public function actions()
    {
        return [
            'editCell' => [
                'class' => EditCellAction::className(),
                'modelClass' => SellingProduct::className(),
            ],
        ];
    }
    
    public function actionChangePack($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return NomenclatureService::changePack($id, Yii::$app->request->post());
    }

    public function actionChangeCurrency($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return NomenclatureService::changeCurrencyByPost($id, Yii::$app->request->post());
    }
}
