<?php


namespace forma\components;


use Yii;
use yii\web\Controller as C;

class Controller extends C
{
    public function beforeAction($action)
    {
        if (parent::beforeAction($action)){
            Yii::debug($_GET);
            if (isset($_GET['form-without-header'])) {

            }
            return true;
        } // TODO: Change the autogenerated stub

        return false;
    }

    public function redirect($url, $statusCode = 302)
    {
        if (isset($_GET['form-without-header']) || isset($_GET['without-header'])) {
            $newUrl = '';
            if (is_string($url)){
                if(strpos($url, '?') !== false) {
                    $newUrl = explode('?', $url)[0].'?without-header&'.explode('?', $url)[1];
                } else $newUrl = $url.'?without-header';
            }
            else {
                $url['without-header'] = '';
                $newUrl = $url;
            }
            return parent::redirect($newUrl, $statusCode);
        }
        return parent::redirect($url, $statusCode); // TODO: Change the autogenerated stub
    }
}